---
- name: Get JunoOS Facts
  hosts: all
  gather_facts: false
  connection: local

  tasks:

  - name: collect default set of facts
    junos_facts:
      gather_subset: config
    
  - name: Print JunOS facts to console
    debug:
      msg: "{{ ansible_facts }}"